#!/usr/bin/env bash
# script to copy file from host to server


if [ $# -ne 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file=$1
ip=$2
username=$3
ssh_key=$4

scp -i ssh_key file username@ip:~/
