#!/usr/bin/env bash
# Script to do task2

sudo apt-get update
sudo apt-get install nginx

sed -i "s@try_files \$uri \$uri/ =404;@try_files \$uri \$uri/ =404;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}@" /etc/nginx/sites-available/default

sudo service nginx restart
