#!/usr/bin/env bash
# Script to do task2

sudo apt-get update
sudo apt-get install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /etc/nginx/html/index.html

sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
