#!/usr/bin/env bash
# Script to do task2

sudo apt-get update
sudo apt-get install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
