#!/usr/bin/env bash
# Script to do task2

apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404 {
        root /etc/nginx/html;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
