#!/usr/bin/env bash
# this configures the web server and adds custom http resonse header

var=$(hostname)

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html

sudo mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf "%s\n" "error_page 404 /custom_404.html;" \
"location /redirect_me {" \
"return 301 \$scheme://www.google.com;" \
"}" \
"server {" \
"add_header X-Served-By $var;" \
"listen 80;" \
"listen [::]:80 default_server;" \
"root /etc/nginx/html;" \
"index index.html index.htm;" \
"location /404 {" \
"root /etc/nginx/html;" \
"internal;" \
"}" \
"}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx start
