#!/usr/bin/env bash
# this configures the web server and adds custom http resonse header
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default


mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default



sudo sed -i '/server_tokens off;/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx start
