#!/usr/bin/env bash
# code to configure load balancer

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 54.160.116.97:80 check
    server web-02 34.207.155.110:80 check
EOF

sudo service haproxy restart
