#!/usr/bin/env bash
# configures nginx to run and listen to port 80

mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.old
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
