#!/usr/bin/env bash
# this code prints best school 10 times
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i = 4 ]
    then
	    echo "bad luck"
    elif [ $i = 8 ]
    then 
	    echo "good luck"
    fi
    i=$((i+1))
done
