#!/usr/bin/env bash
# this code prints best school 10 times
i=1
while [ $i -le 20 ]
do
    case "$i" in
	    4)
	    echo "$i"
	    echo "bad luck from China"
	    ;;
	    9)
	    echo "$i"
	    echo "bad luck from Japan"
	    ;; 
	    14)
	    echo "$i"
	    echo "bad luck from Italy"
	    ;;
    *)
	    echo "$i";;
	esac
    i=$((i+1))
done
